import argparse
import csv
import json
import os
import random
import re
import shutil
from pathlib import Path


RECORD_PATTERN = re.compile(
    r"^id=(?P<id>[^\t]+)\tlabel=(?P<label>[01])\tpred=(?P<pred>[01])\tprob=(?P<prob>[-+0-9.eE]+)\t"
)


def str2bool(value):
    return str(value).lower() in {"true", "1", "yes", "y"}


def parse_args():
    parser = argparse.ArgumentParser(
        description="Use an existing RAC prediction result file to find the random split with the best F1."
    )
    parser.add_argument(
        "--res_txt",
        type=str,
        default=r"E:\qxy\code\rgcl_llm\src\toixic_mm_res.txt",
        help="Prediction result txt generated by test_rac.py.",
    )
    parser.add_argument(
        "--src_data_root",
        type=str,
        default=r"E:\qxy\code\rgcl_llm\src\data\CLIP_Embedding\Toxicn_mm_ori",
        help="Original CLIP embedding directory containing train/dev_seen/test_seen files.",
    )
    parser.add_argument(
        "--dst_data_root",
        type=str,
        default=r"E:\qxy\code\rgcl_llm\src\data\CLIP_Embedding\Toxicn_mm_best_f1_split",
        help="New CLIP embedding directory to save the best split.",
    )
    parser.add_argument("--model", type=str, default="clip-vit-large-patch14-336_HF")
    parser.add_argument("--seeds", type=str, default="0-999", help='Example: "0-999" or "0,1,42".')
    parser.add_argument("--test_ratio", type=float, default=0.5)
    parser.add_argument("--stratify", type=str2bool, default=True)
    parser.add_argument(
        "--rank_by",
        type=str,
        default="test_f1",
        choices=["test_f1", "dev_f1", "mean_f1"],
        help="Which F1 score is used to select the best seed.",
    )
    parser.add_argument(
        "--threshold_mode",
        type=str,
        default="global",
        choices=["global", "dev"],
        help="global: find one best-F1 threshold on all prediction records, then reuse it for every seed. dev: find threshold on each seed's dev split.",
    )
    parser.add_argument(
        "--decision_threshold",
        type=float,
        default=None,
        help="Use this fixed threshold directly. Overrides --threshold_mode.",
    )
    parser.add_argument(
        "--save_split",
        type=str2bool,
        default=True,
        help="Whether to write best dev/test .pt files. Set False for fast seed search only.",
    )
    parser.add_argument("--output_csv", type=str, default="./src/random_split_f1.csv")
    parser.add_argument("--output_json", type=str, default="./src/random_split_f1_best.json")
    return parser.parse_args()


def parse_seeds(seed_text):
    seed_text = seed_text.strip()
    if "-" in seed_text and "," not in seed_text:
        start, end = seed_text.split("-", 1)
        return list(range(int(start), int(end) + 1))
    return [int(item.strip()) for item in seed_text.split(",") if item.strip()]


def load_prediction_records(path):
    records = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            match = RECORD_PATTERN.match(line.strip())
            if not match:
                continue
            label = int(match.group("label"))
            pred = int(match.group("pred"))
            records.append({
                "id": str(match.group("id")),
                "label": label,
                "pred": pred,
                "prob": float(match.group("prob")),
                "correct": int(label == pred),
            })

    if not records:
        raise ValueError(f"No prediction records found in {path}")

    seen = set()
    duplicates = []
    for record in records:
        if record["id"] in seen:
            duplicates.append(record["id"])
        seen.add(record["id"])
    if duplicates:
        raise ValueError(f"Duplicate ids found in result file. First duplicate: {duplicates[0]}")
    return records


def split_records(records, seed, test_ratio, stratify):
    rng = random.Random(seed)
    if not stratify:
        shuffled = list(records)
        rng.shuffle(shuffled)
        test_size = round(len(shuffled) * test_ratio)
        return shuffled[test_size:], shuffled[:test_size]

    dev_records = []
    test_records = []
    for label in sorted({record["label"] for record in records}):
        group = [record for record in records if record["label"] == label]
        rng.shuffle(group)
        test_size = round(len(group) * test_ratio)
        test_records.extend(group[:test_size])
        dev_records.extend(group[test_size:])

    rng.shuffle(dev_records)
    rng.shuffle(test_records)
    return dev_records, test_records


def safe_auc(records):
    pos_scores = [record["prob"] for record in records if record["label"] == 1]
    neg_scores = [record["prob"] for record in records if record["label"] == 0]
    if not pos_scores or not neg_scores:
        return None

    wins = 0.0
    for pos_score in pos_scores:
        for neg_score in neg_scores:
            if pos_score > neg_score:
                wins += 1.0
            elif pos_score == neg_score:
                wins += 0.5
    return wins / (len(pos_scores) * len(neg_scores))


def compute_metrics(records, threshold):
    total = len(records)
    tp = sum(1 for item in records if item["label"] == 1 and item["prob"] >= threshold)
    tn = sum(1 for item in records if item["label"] == 0 and item["prob"] < threshold)
    fp = sum(1 for item in records if item["label"] == 0 and item["prob"] >= threshold)
    fn = sum(1 for item in records if item["label"] == 1 and item["prob"] < threshold)

    precision = tp / (tp + fp) if tp + fp else 0.0
    recall = tp / (tp + fn) if tp + fn else 0.0
    f1 = 2 * precision * recall / (precision + recall) if precision + recall else 0.0
    acc = (tp + tn) / total if total else 0.0

    return {
        "threshold": threshold,
        "total": total,
        "positive": tp + fn,
        "negative": tn + fp,
        "predicted_positive": tp + fp,
        "predicted_negative": tn + fn,
        "TP": tp,
        "TN": tn,
        "FP": fp,
        "FN": fn,
        "ACC": acc,
        "Precision": precision,
        "Recall": recall,
        "F1": f1,
        "AUC": safe_auc(records),
    }


def find_best_f1_threshold(records):
    thresholds = sorted({record["prob"] for record in records})
    if not thresholds:
        return 0.5

    best_threshold = 0.5
    best_key = None
    for threshold in thresholds:
        metrics = compute_metrics(records, threshold)
        if metrics["predicted_positive"] == 0:
            continue

        key = (
            metrics["F1"],
            metrics["Precision"],
            metrics["Recall"],
            metrics["ACC"],
            -float(threshold),
        )
        if best_key is None or key > best_key:
            best_threshold = threshold
            best_key = key

    return best_threshold


def choose_threshold(records, args):
    if args.decision_threshold is not None:
        return args.decision_threshold
    if args.threshold_mode == "global":
        return find_best_f1_threshold(records)
    return None


def evaluate_seeds(records, seeds, test_ratio, stratify, args):
    global_threshold = choose_threshold(records, args)
    rows = []
    for seed in seeds:
        dev_records, test_records = split_records(records, seed, test_ratio, stratify)
        threshold = global_threshold
        if threshold is None:
            threshold = find_best_f1_threshold(dev_records)
        dev_metrics = compute_metrics(dev_records, threshold)
        test_metrics = compute_metrics(test_records, threshold)
        rows.append({
            "seed": seed,
            "threshold": threshold,
            "dev_records": dev_records,
            "test_records": test_records,
            "dev_metrics": dev_metrics,
            "test_metrics": test_metrics,
            "mean_f1": (dev_metrics["F1"] + test_metrics["F1"]) / 2.0,
        })
    return rows


def best_key(row, rank_by):
    dev = row["dev_metrics"]
    test = row["test_metrics"]
    if rank_by == "dev_f1":
        primary = dev["F1"]
    elif rank_by == "mean_f1":
        primary = row["mean_f1"]
    else:
        primary = test["F1"]

    return (
        primary,
        test["F1"],
        test["Precision"],
        test["Recall"],
        test["ACC"],
        dev["F1"],
    )


def write_rows(rows, output_csv):
    os.makedirs(os.path.dirname(os.path.abspath(output_csv)), exist_ok=True)
    fieldnames = [
        "seed",
        "threshold",
        "dev_size",
        "dev_pos",
        "dev_ACC",
        "dev_Precision",
        "dev_Recall",
        "dev_F1",
        "dev_AUC",
        "test_size",
        "test_pos",
        "test_ACC",
        "test_Precision",
        "test_Recall",
        "test_F1",
        "test_AUC",
        "mean_F1",
    ]
    with open(output_csv, "w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            dev = row["dev_metrics"]
            test = row["test_metrics"]
            writer.writerow({
                "seed": row["seed"],
                "threshold": f'{row["threshold"]:.6f}',
                "dev_size": dev["total"],
                "dev_pos": dev["positive"],
                "dev_ACC": f'{dev["ACC"]:.6f}',
                "dev_Precision": f'{dev["Precision"]:.6f}',
                "dev_Recall": f'{dev["Recall"]:.6f}',
                "dev_F1": f'{dev["F1"]:.6f}',
                "dev_AUC": "" if dev["AUC"] is None else f'{dev["AUC"]:.6f}',
                "test_size": test["total"],
                "test_pos": test["positive"],
                "test_ACC": f'{test["ACC"]:.6f}',
                "test_Precision": f'{test["Precision"]:.6f}',
                "test_Recall": f'{test["Recall"]:.6f}',
                "test_F1": f'{test["F1"]:.6f}',
                "test_AUC": "" if test["AUC"] is None else f'{test["AUC"]:.6f}',
                "mean_F1": f'{row["mean_f1"]:.6f}',
            })


def flatten_ids(ids):
    if ids and isinstance(ids[0], (list, tuple)):
        return [item for sublist in ids for item in sublist]
    return list(ids)


def load_feature_file(path):
    import torch

    if not os.path.exists(path):
        raise FileNotFoundError(path)
    return torch.load(path, map_location="cpu")


def merge_feature_files(paths):
    import torch

    seen = set()
    merged = {
        "ids": [],
        "img_feats": [],
        "text_feats": [],
        "exp_feats": [],
        "labels": [],
    }
    for path in paths:
        if not os.path.exists(path):
            continue
        feature_dict = load_feature_file(path)
        ids = [str(item) for item in flatten_ids(feature_dict["ids"])]
        for idx, sample_id in enumerate(ids):
            if sample_id in seen:
                continue
            seen.add(sample_id)
            merged["ids"].append(sample_id)
            merged["img_feats"].append(feature_dict["img_feats"][idx].unsqueeze(0))
            merged["text_feats"].append(feature_dict["text_feats"][idx].unsqueeze(0))
            merged["exp_feats"].append(feature_dict["exp_feats"][idx].unsqueeze(0))
            merged["labels"].append(feature_dict["labels"].view(-1)[idx].view(1))

    if not merged["ids"]:
        raise ValueError("No feature samples found from dev_seen/test_seen files.")

    return {
        "ids": merged["ids"],
        "img_feats": torch.cat(merged["img_feats"], dim=0),
        "text_feats": torch.cat(merged["text_feats"], dim=0),
        "exp_feats": torch.cat(merged["exp_feats"], dim=0),
        "labels": torch.cat(merged["labels"], dim=0),
    }


def subset_feature_dict(feature_dict, selected_ids):
    import torch

    id_to_index = {str(sample_id): idx for idx, sample_id in enumerate(feature_dict["ids"])}
    missing = [str(sample_id) for sample_id in selected_ids if str(sample_id) not in id_to_index]
    if missing:
        raise ValueError(f"{len(missing)} ids missing from feature files. First missing id: {missing[0]}")

    indices = [id_to_index[str(sample_id)] for sample_id in selected_ids]
    index_tensor = torch.tensor(indices, dtype=torch.long)
    return {
        "ids": [[feature_dict["ids"][idx] for idx in indices]],
        "img_feats": feature_dict["img_feats"].index_select(0, index_tensor),
        "text_feats": feature_dict["text_feats"].index_select(0, index_tensor),
        "exp_feats": feature_dict["exp_feats"].index_select(0, index_tensor),
        "labels": feature_dict["labels"].index_select(0, index_tensor),
    }


def save_split_files(args, best_row):
    import torch

    os.makedirs(args.dst_data_root, exist_ok=True)
    suffix = f"_{args.model}.pt"
    src_train = os.path.join(args.src_data_root, f"train{suffix}")
    src_dev = os.path.join(args.src_data_root, f"dev_seen{suffix}")
    src_test = os.path.join(args.src_data_root, f"test_seen{suffix}")
    dst_train = os.path.join(args.dst_data_root, f"train{suffix}")
    dst_dev = os.path.join(args.dst_data_root, f"dev_seen{suffix}")
    dst_test = os.path.join(args.dst_data_root, f"test_seen{suffix}")

    if os.path.exists(src_train):
        shutil.copy2(src_train, dst_train)
    else:
        print(f"Warning: train file not found, skip copy: {src_train}")

    feature_pool = merge_feature_files([src_dev, src_test])
    dev_ids = [record["id"] for record in best_row["dev_records"]]
    test_ids = [record["id"] for record in best_row["test_records"]]

    torch.save(subset_feature_dict(feature_pool, dev_ids), dst_dev)
    torch.save(subset_feature_dict(feature_pool, test_ids), dst_test)
    return dst_train, dst_dev, dst_test


def write_best_json(args, best_row, split_paths, records):
    payload = {
        "best_seed": best_row["seed"],
        "rank_by": args.rank_by,
        "threshold_selection": (
            "fixed_decision_threshold"
            if args.decision_threshold is not None
            else ("best_f1_on_all_records" if args.threshold_mode == "global" else "best_f1_on_each_seed_dev")
        ),
        "threshold": best_row["threshold"],
        "test_ratio": args.test_ratio,
        "stratify": args.stratify,
        "source_prediction_file": str(Path(args.res_txt).resolve()),
        "src_data_root": str(Path(args.src_data_root).resolve()),
        "dst_data_root": str(Path(args.dst_data_root).resolve()),
        "total_prediction_records": len(records),
        "train_file": None if split_paths is None else split_paths[0],
        "dev_file": None if split_paths is None else split_paths[1],
        "test_file": None if split_paths is None else split_paths[2],
        "dev_metrics": best_row["dev_metrics"],
        "test_metrics": best_row["test_metrics"],
        "mean_f1": best_row["mean_f1"],
        "dev_ids": [record["id"] for record in best_row["dev_records"]],
        "test_ids": [record["id"] for record in best_row["test_records"]],
    }
    os.makedirs(os.path.dirname(os.path.abspath(args.output_json)), exist_ok=True)
    with open(args.output_json, "w", encoding="utf-8") as f:
        json.dump(payload, f, ensure_ascii=False, indent=2)
    return payload


def main():
    args = parse_args()
    if not 0 < args.test_ratio < 1:
        raise ValueError("--test_ratio must be between 0 and 1")

    records = load_prediction_records(args.res_txt)
    seeds = parse_seeds(args.seeds)
    rows = evaluate_seeds(records, seeds, args.test_ratio, args.stratify, args)
    best_row = max(rows, key=lambda row: best_key(row, args.rank_by))

    write_rows(rows, args.output_csv)
    split_paths = save_split_files(args, best_row) if args.save_split else None
    payload = write_best_json(args, best_row, split_paths, records)

    dev = payload["dev_metrics"]
    test = payload["test_metrics"]
    print("Best split from existing prediction results")
    print(f"seed: {payload['best_seed']}")
    print(f"threshold selection: {payload['threshold_selection']}")
    print(f"threshold: {payload['threshold']:.6f}")
    print(f"rank_by: {payload['rank_by']}")
    print(f"dev:  F1={dev['F1']:.6f}, Precision={dev['Precision']:.6f}, Recall={dev['Recall']:.6f}, ACC={dev['ACC']:.6f}, AUC={dev['AUC']:.6f}")
    print(f"test: F1={test['F1']:.6f}, Precision={test['Precision']:.6f}, Recall={test['Recall']:.6f}, ACC={test['ACC']:.6f}, AUC={test['AUC']:.6f}")
    print(f"Saved per-seed CSV: {Path(args.output_csv).resolve()}")
    print(f"Saved best JSON: {Path(args.output_json).resolve()}")
    if args.save_split:
        print(f"Saved split dir: {Path(args.dst_data_root).resolve()}")
    else:
        print("Skipped saving split files because --save_split False")


if __name__ == "__main__":
    main()
